/**
 * Every number, name, and URL in this file is written by hand and reviewed by a
 * person. Nothing on this path is ever generated by a language model, and no
 * caller may pass a contact detail in from outside this module.
 */

export const crisisLocaleValues = ["international", "cz", "gb", "us"] as const;

export type CrisisLocale = (typeof crisisLocaleValues)[number];

export type CrisisResource = {
  contact: string;
  description: string;
  name: string;
  url?: string;
};

export type CrisisLocaleResources = {
  emergency: string;
  label: string;
  resources: CrisisResource[];
};

export const NOT_EQUIPPED_STATEMENT =
  "NoemaForge is not equipped to handle a crisis. No one reads what you write here, nothing you write raises an alert, and the app cannot contact anyone on your behalf.";

const crisisResourcesByLocale: Record<CrisisLocale, CrisisLocaleResources> = {
  cz: {
    emergency: "112",
    label: "Czechia",
    resources: [
      {
        contact: "116 123",
        description: "Free emotional support line, around the clock.",
        name: "Linka první psychické pomoci",
      },
      {
        contact: "116 111",
        description: "Free line for people under 26, around the clock.",
        name: "Linka bezpečí",
      },
    ],
  },
  gb: {
    emergency: "999",
    label: "United Kingdom",
    resources: [
      {
        contact: "116 123",
        description: "Free from any phone, around the clock.",
        name: "Samaritans",
      },
      {
        contact: "Text SHOUT to 85258",
        description: "Free text support, around the clock.",
        name: "Shout",
      },
    ],
  },
  international: {
    emergency: "your local emergency number",
    label: "International",
    resources: [
      {
        contact: "findahelpline.com",
        description: "Verified crisis lines in over one hundred countries.",
        name: "Find a Helpline",
        url: "https://findahelpline.com",
      },
      {
        contact: "iasp.info/resources/Crisis_Centres",
        description: "Directory of crisis centres by country.",
        name: "International Association for Suicide Prevention",
        url: "https://www.iasp.info/resources/Crisis_Centres/",
      },
    ],
  },
  us: {
    emergency: "911",
    label: "United States",
    resources: [
      {
        contact: "Call or text 988",
        description: "Free, around the clock, in English and Spanish.",
        name: "988 Suicide and Crisis Lifeline",
      },
      {
        contact: "Text HOME to 741741",
        description: "Free text support, around the clock.",
        name: "Crisis Text Line",
      },
    ],
  },
};

export function getCrisisResources(locale: CrisisLocale): CrisisLocaleResources {
  return crisisResourcesByLocale[locale];
}
